import Foundation

/// Lightweight in-app localization, ported from the TRANSLATIONS dict in
/// the original app.py. Kept as a plain dictionary (rather than
/// Localizable.strings) so behavior - including runtime language
/// switching from Settings - matches the original exactly.
enum Loc {
    static let languages: [(name: String, code: String)] = [
        ("English", "en"),
        ("Русский", "ru"),
        ("Українська", "uk"),
        ("Polski", "pl"),
    ]

    static func t(_ key: String, lang: String, _ args: CVarArg...) -> String {
        let dict = table[lang] ?? table["en"]!
        let raw = dict[key] ?? table["en"]?[key] ?? key
        return args.isEmpty ? raw : String(format: raw, arguments: args)
    }

    static let table: [String: [String: String]] = [
        "en": [
            "app_title": "LocAI",
            "app_subtitle": "A local model chat assistant",
            "tab_chat": "Chat",
            "tab_models": "Models",
            "tab_settings": "Settings",
            "tab_tuning": "Tuning",
            "loaded_model": "Loaded model:",
            "no_model_loaded": "No model loaded",
            "send": "Send",
            "clear_chat": "Clear chat",
            "web_search": "Search web",
            "save_chat": "Save chat",
            "backend": "Backend:",
            "search_label": "Search Hugging Face",
            "search_button": "Search",
            "quick_picks": "Quick picks",
            "repos_found": "Repos found",
            "files_label_gguf": "GGUF files (pick a quantization)",
            "files_label_mlx": "MLX repo (whole folder is downloaded)",
            "download_selected": "Download selected",
            "downloaded_models": "Downloaded models",
            "ready": "Ready",
            "generation_complete": "Done",
            "max_memory": "Max memory budget for the model (GB)",
            "force_swap": "Allow models bigger than my budget (disk swap, slower)",
            "forced_swap_frame": "Forced swap mode",
            "load_model_first": "Load a model from the Models tab first.",
            "generation_error": "Generation error",
            "system_memory": "System memory: %.1f / %.1f GB used",
            "free_disk": "Free disk: %.1f GB",
            "select_language": "Language",
            "continue_response": "Allow longer responses (up to 4k tokens)",
            "system_prompt_frame": "System prompt (model instruction)",
            "tuning_header": "Fine-tune with LoRA / QLoRA",
            "tuning_note": "Not yet ported to Swift - MLX Swift training loop is planned.",
            "delete_selected": "Delete selected",
            "delete_confirm_title": "Delete this model?",
            "models_folder": "Models folder",
        ],
        "ru": [
            "app_title": "LocAI",
            "app_subtitle": "Локальный чат с моделями",
            "tab_chat": "Чат",
            "tab_models": "Модели",
            "tab_settings": "Настройки",
            "tab_tuning": "Тюнинг",
            "loaded_model": "Загруженная модель:",
            "no_model_loaded": "Модель не загружена",
            "send": "Отправить",
            "clear_chat": "Очистить",
            "web_search": "Поиск в интернете",
            "save_chat": "Сохранить чат",
            "backend": "Бэкенд:",
            "search_label": "Поиск на Hugging Face",
            "search_button": "Поиск",
            "quick_picks": "Быстрый выбор",
            "repos_found": "Найдено репозиториев",
            "files_label_gguf": "GGUF файлы (выберите квантизацию)",
            "files_label_mlx": "MLX репозиторий (загружается целиком)",
            "download_selected": "Скачать",
            "downloaded_models": "Скачанные модели",
            "ready": "Готово",
            "generation_complete": "Готово",
            "max_memory": "Макс. память для модели (ГБ)",
            "force_swap": "Разрешить модели больше бюджета (swap, медленнее)",
            "forced_swap_frame": "Режим принудительного swap",
            "load_model_first": "Сначала загрузите модель на вкладке Модели.",
            "generation_error": "Ошибка генерации",
            "system_memory": "Память системы: %.1f / %.1f ГБ использовано",
            "free_disk": "Свободно на диске: %.1f ГБ",
            "select_language": "Язык",
            "continue_response": "Разрешить более длинные ответы (до 4k токенов)",
            "system_prompt_frame": "Системный промпт (инструкция модели)",
            "tuning_header": "Дообучение LoRA / QLoRA",
            "tuning_note": "Ещё не портировано на Swift - планируется цикл обучения на MLX Swift.",
            "delete_selected": "Удалить выбранное",
            "delete_confirm_title": "Удалить эту модель?",
            "models_folder": "Папка моделей",
        ],
        "uk": [
            "app_title": "LocAI",
            "app_subtitle": "Локальний чат з моделями",
            "tab_chat": "Чат",
            "tab_models": "Моделі",
            "tab_settings": "Налаштування",
            "tab_tuning": "Тюнінг",
            "loaded_model": "Завантажена модель:",
            "no_model_loaded": "Модель не завантажена",
            "send": "Відправити",
            "clear_chat": "Очистити",
            "web_search": "Пошук в Інтернеті",
            "save_chat": "Зберегти чат",
            "backend": "Бекенд:",
            "search_label": "Пошук на Hugging Face",
            "search_button": "Пошук",
            "quick_picks": "Швидкий вибір",
            "repos_found": "Знайдено репозиторіїв",
            "files_label_gguf": "GGUF файли (виберіть квантизацію)",
            "files_label_mlx": "MLX репозиторій (завантажується цілком)",
            "download_selected": "Завантажити",
            "downloaded_models": "Завантажені моделі",
            "ready": "Готово",
            "generation_complete": "Готово",
            "max_memory": "Макс. пам'ять для моделі (ГБ)",
            "force_swap": "Дозволити моделі більші за бюджет (swap, повільніше)",
            "forced_swap_frame": "Режим примусового swap",
            "load_model_first": "Спочатку завантажте модель на вкладці Моделі.",
            "generation_error": "Помилка генерації",
            "system_memory": "Пам'ять системи: %.1f / %.1f ГБ використано",
            "free_disk": "Вільно на диску: %.1f ГБ",
            "select_language": "Мова",
            "continue_response": "Дозволити довші відповіді (до 4k токенів)",
            "system_prompt_frame": "Системний промпт (інструкція моделі)",
            "tuning_header": "Дотюнінг LoRA / QLoRA",
            "tuning_note": "Ще не портовано на Swift - плануємо цикл навчання на MLX Swift.",
            "delete_selected": "Видалити вибране",
            "delete_confirm_title": "Видалити цю модель?",
            "models_folder": "Папка моделей",
        ],
        "pl": [
            "app_title": "LocAI",
            "app_subtitle": "Lokalny czat z modelami",
            "tab_chat": "Czat",
            "tab_models": "Modele",
            "tab_settings": "Ustawienia",
            "tab_tuning": "Tuning",
            "loaded_model": "Załadowany model:",
            "no_model_loaded": "Model nie jest załadowany",
            "send": "Wyślij",
            "clear_chat": "Wyczyść",
            "web_search": "Wyszukiwanie w sieci",
            "save_chat": "Zapisz czat",
            "backend": "Backend:",
            "search_label": "Szukaj na Hugging Face",
            "search_button": "Szukaj",
            "quick_picks": "Szybki wybór",
            "repos_found": "Znaleziono repozytoriów",
            "files_label_gguf": "Pliki GGUF (wybierz kwantyzację)",
            "files_label_mlx": "Repozytorium MLX (całość jest pobierana)",
            "download_selected": "Pobierz",
            "downloaded_models": "Pobrane modele",
            "ready": "Gotowe",
            "generation_complete": "Gotowe",
            "max_memory": "Maksymalny budżet pamięci (GB)",
            "force_swap": "Pozwól na modele większe niż budżet (swap, wolniej)",
            "forced_swap_frame": "Tryb wymuszonego swap",
            "load_model_first": "Najpierw załaduj model na karcie Modele.",
            "generation_error": "Błąd generowania",
            "system_memory": "Pamięć systemowa: %.1f / %.1f GB użyte",
            "free_disk": "Wolne miejsce: %.1f GB",
            "select_language": "Język",
            "continue_response": "Pozwól na dłuższe odpowiedzi (do 4k tokenów)",
            "system_prompt_frame": "Systemowy prompt (instrukcja modelu)",
            "tuning_header": "Douczanie LoRA / QLoRA",
            "tuning_note": "Jeszcze nie przeniesione na Swift - planowana pętla treningowa MLX Swift.",
            "delete_selected": "Usuń zaznaczone",
            "delete_confirm_title": "Usunąć ten model?",
            "models_folder": "Folder modeli",
        ],
    ]
}
